# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.CharField(max_length=2000),
        ),
    ]
