# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_auto_20170202_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='github',
            new_name='facebook',
        ),
    ]
